---
collections:
  - name: awx.awx
  - name: redhat_cop.controller_configuration
  - name: redhat_cop.tower_utilities
  - name: redhat.rhel_system_roles
  - name: community.aws
  - name: community.general
  - name: community.mysql
  - name: containers.podman
  - name: infra.controller_configuration
  - name: community.crypto
  - name: chocolatey.chocolatey
  - name: community.windows
